### ISSUE TITLE
copy mode vs easyjump

### ISSUE THREAD

**Issue by askurihin** [roy2220/easyjump.tmux#1]
Hello!
Great plugin, thank you for your work.

It would be very useful, if this plugin could allow to jump when tmux is in copy mode.

Example:

Some command has produced several screens of output, I activate copy mode, scroll one screen up, see information I want to copy, activate easyjump and with a few strokes I'm in the right position.

Current behavior:

Copy mode exists after I activate easyjump and thus resets my current cursor position and there is no way to jump
where I want.

**Comment by roy2220** [comment]
@askurihin Sounds reasonable, I will try to implement this feature.

**Comment by roy2220** [comment]
@askurihin This lovely feature has been supported 🎉, check it out!

**Comment by askurihin** [comment]
Wow, that was fast!
Works like a charm, thank you a lot.
