### ISSUE TITLE
[Bug report] Other texts invisible when selecting matches

### ISSUE THREAD

**Issue by kohane27** [roy2220/easyjump.tmux#12]
Hello! Thank you for creating such an awesome tmux plugin. I really like "searching by 2 chars" feature. However, I'm having the following issue:

https://user-images.githubusercontent.com/57322459/166424231-acf7b89b-de7a-4f5b-bfa3-9be75107fa31.mp4

![screenshot-2022-05-03-16-26-49](https://user-images.githubusercontent.com/57322459/166424048-1a9bf722-5e86-47e1-b084-76cb87573dbd.png)

After inputting two characters, I can't see anything except the highlighted first char of potential matches. All other texts are darkened.

Is it the problem with my terminal? Here's what I tried but none worked:

1. I'm using `kitty` but the same iusse persisted with `alacritty`

2. tried different colorschemes in `kitty`

My config:

```
set-option -g @plugin "roy2220/easyjump.tmux"
set-option -g @easyjump-key-binding "f"
set-option -g @easyjump-smart-case "off"
set-option -g @easyjump-auto-begin-selection "on"
```

Is it possible that you add an option to "disable darkened other texts when selecting potential matches"? The first char being orange is apparent enough (at least for me).

Any help is much appreciated. Thank you!

**Comment by roy2220** [comment]
Hi @kohane27 the darkened text is caused by the default option `set-option -g @easyjump-text-attrs "\e[0m\e[38;5;237m"`, you can change the color of the text easily (see https://misc.flogisoft.com/bash/tip_colors_and_formatting).

Only changing the color of the first char will incur another problem when the color of the first char happens to be orange already, in this case there is no difference can be recognized.

**Comment by kohane27** [comment]
@roy2220 Sorry to be calling it a bug report and for missing out the doc. My sincere apologies.

For anyone having similar issue: I simply changed the attribute `@easyjump-text-attrs` from `\e[0m\e[38;5;237m` to `\e[0m`, i.e., `set-option -g @easyjump-text-attrs "\e[0m"`. Here's the result while selecting the target:

![screenshot-2022-05-12-13-43-18](https://user-images.githubusercontent.com/57322459/168000897-f30ef893-9fe6-40d5-87dd-e0f9e82f3f31.png)

The `\e[0m` sequence removes all attributes (formatting and colors). For some reason (maybe my particular terminal (kitty) and terminal theme), `\e[38;5;237m` is the culprit. Issuing the command `echo -e "\e[0mHello\e[38;5;237mWorld"` and I can only see the "hello" but not the "world".

Thanks again!
