### ISSUE TITLE
[FeatureRequest] Keep cursor position after exit copy-mode

### ISSUE THREAD

**Issue by hiberabyss** [roy2220/easyjump.tmux#4]
When edit long command (e.g. shell commands or mysql queries), I want to use easyjump to go to the right position and do the edits.

Thanks for creating this plugin!

**Comment by roy2220** [comment]
As far as I know, these programs (e.g. shell, MySQL client) keep/track the cursor position on their own. In order to achieve this, some plugins for these programs may be required to cooperate with (that's the reason I created the Vim plugin). I will take some time to investigate the feasibility.

**Comment by roy2220** [comment]
It's unfeasible, close it now.
