### ISSUE TITLE
Jumping across vim splits is throwing error

### ISSUE THREAD

**Issue by intrntbrn** [roy2220/easyjump.tmux#5]
Thank you this great plugin! I noticed that the plugin does not work properly when having more than 2 splits in (n)vim.

Assume we have the following split layout:
`1 | 2 | 3`

I can jump from 1 to 2, and from 2 to 3. However, trying to jump from 1 to 3 is throwing an error. This always seem to happen when there is at least one additional split between origin and destination.

```
Error detected while processing function <SNR>104_invoke:
line   26:
Traceback (most recent call last):^@  File "/home/int/.vim/plugged/easyjump.tmux/plugin/../easyjump.py", line 553, in <module>^@    main()^@  File "/home/int/.vim/plugged/easyjump.tmux/plugin/../easyjump.py", line 549, in main^@    screen.jump_to_position(position)^@  File "/home/int/.vim/plugged/easyjump.tmux/plugin/../easyjump.py", line 210, in jump_to_position^@    self._mouse_jump_to_position(position)^@  Fil
e "/home/int/.vim/plugged/easyjump.tmux/plugin/../easyjump.py", line 256, in _mouse_jump_to_position^@    x = bytes((0x20 + position.column_number,))^@ValueError: bytes must be in range(0, 256)^@
```

**Comment by roy2220** [comment]
Seems the X10 mouse protocol limit is reached.

> The original X10 mouse protocol limits the Cx and Cy ordinates to 223 (=255 - 32). XTerm supports more than one scheme for extending this range, by changing the protocol encoding: ...

I will follow it up.

**Comment by intrntbrn** [comment]
Right, it's actually pixel distance and i can trigger the error even without splits. 

I am using a tiny bitmap font on 2560x1440 screens, so i am probably having more cells than others and therefore i am more likely to trigger the overflow.

**Comment by roy2220** [comment]
@intrntbrn Fixed, check it out.

**Comment by intrntbrn** [comment]
Seems fixed. Thank you!
