### ISSUE TITLE
[Feature Request] Improve length of label characters

### ISSUE THREAD

**Issue by laggardkernel** [roy2220/easyjump.tmux#7]
`easyjump.tmux` begins with 1 char label. If 1 char is not enough to differentiate the occurrences, it switches to using 2 character.

The problem is the length of labels ( 1 or 2 characters) is set globally. We could improve it to use both 1 char labels and 2 char labels at the same time when there's too many occurrences.

**Comment by roy2220** [comment]
Good point. Will try implementing this feature when I'm free, hope not too many changes.

**Comment by roy2220** [comment]
@laggardkernel implemented, check it out :)

**Comment by laggardkernel** [comment]
Seems there's some problem in this implementation. I get 2 char labels, but type 2 char label doesn't make my cursor jump to the target now.

**Comment by roy2220** [comment]
@laggardkernel I can't reproduce the bug. Can you provide the context to reproduce it?

**Comment by laggardkernel** [comment]
https://asciinema.org/a/KUNaJBi0nT7rrCLLurenvndLO

Environment

- tmux 3.2a
- Terminal: kitty 0.21.2
- `TERM`: `xterm-kitty` outside tmux, `screen` inside tmux

**Comment by roy2220** [comment]
@laggardkernel I noticed that the code of the plugin in your environment seems not the latest, a bug I have fixed reoccurred in your demonstration, try reinstalling the plugin or updating the repo of the plugin manually (`git fetch origin && git reset --hard origin/master`).

**Comment by laggardkernel** [comment]
You're right. Seems you force pushed the commit and I didn't get the latest change. A rebase pull fixed my problem. Many thanks.
